_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  webform_clientside_validation: -1
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advagg: 0
  announcements_feed: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contact: 0
  contextual: 0
  csp: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  devel_php: 0
  ds_devel: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  imce: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  libraries_ui: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_extended_perms: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  permissionspolicy: 0
  quick_node_clone: 0
  redirect: 0
  reroute_email: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_limit: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  ds: 1
  pathauto: 1
  webform_bootstrap: 1
  ds_extras: 2
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap: 0
  bartik: 0
  stable: 0
  classy: 0
  smallbusiness: 0
profile: standard
